<?php
/**
 * @file
 * General hook implementations.
 */

const DGI_ISLANDORA_SOLR_VIEWS_FIELD_FILTER_CACHE_FILENAME = 'temporary://dgi_islandora_solr_views_field_filter_fields.json'
const DGI_ISLANDORA_SOLR_VIEWS_FIELD_FILTER_REGEX_EXCLUDE_DEFAULT = '!RELS_EXT_(?:http://islandora\.ca/ontology/relsext#)?isSequenceNumberOf.+_literal.+!';

/**
 * Implements hook_menu().
 */
function dgi_islandora_solr_views_field_filter_menu() {
  $item = array();

  $item['admin/islandora/tools/dgi_solr_views_field_filter'] = array(
    'title' => 'Solr Views Field Filter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dgi_islandora_solr_views_field_filter_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );

  return $item;
}

/**
 * Implements hook_module_implements_alter().
 */
function dgi_islandora_solr_views_field_filter_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'views_data') {
    unset($implementations['islandora_solr_views']);
  }
}

/**
 * Implements hook_views_api().
 */
function dgi_islandora_solr_views_field_filter_views_api() {
  return array('api' => '3.0');
}

/**
 * Implements hook_flush_caches().
 */
function dgi_islandora_solr_views_field_filter_flush_caches() {
  // XXX: Not quite documented use of this hook; however, allowances for this
  // type of usage has been allowed for in core modules, in particular, the
  // invocation of this hook is minimized in system_cron().
  // ... so... let's follow suit, and nuke our cache.
  module_load_include('views.inc', 'dgi_islandora_solr_views_field_filter');
  $file = _dgi_islandora_solr_views_field_filter_get_file();
  if ($file) {
    file_delete($file);
  }
}
